{
 "title": "Evolución de la temperatura",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Estado de la alarma",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "alarm", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Evolución de la temperatura en ºF",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    { "expr": "temp_F", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Evolución de la temperatura en ºC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "temp_C", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Valor de la temperatura en ºF",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "temp_F", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Medida de la temperatura en ºC",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "temp_C", "legendFormat": "__auto" }
   ]
  }
 ]
}