apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: bfag38wxerqbkd
    access: proxy
    url: http://prometheus:9090  # Nombre del servicio en tu docker-compose
    isDefault: true
    editable: false
    jsonData:
      timeInterval: "5s"